#ifndef _MICROP_HTCKOVSKY_H
#define _MICROP_HTCKOVSKY_H

enum kovsky_color_led {
	UPPER_RIGHT = 1,
	UPPER_LEFT = 2,
	LOWER_RIGHT = 4,
	LOWER_LEFT = 8,
	ALL_LEDS = UPPER_LEFT | UPPER_RIGHT | LOWER_LEFT | LOWER_RIGHT,
};

enum kovsky_pattern_cmd {
	DISABLE = 0,
	ENABLE = 1,
	SET_PATTERN = 2,
};

typedef unsigned char kovsky_pattern_t[0x46];

#define PATTERN_MAXSTEPCOUNT			8

#define	MICROP_OJ_POWER_KOVS			0x03
#define MICROP_VERSION_REG_KOVS			0x07
#define MICROP_PATTERN_COMMAND_KOVS		0x11
#define MICROP_LCD_BRIGHTNESS_KOVS		0x12
#define MICROP_LCD_BRIGHTNESS_KOVS_13	0x13
#define MICROP_KEYPAD_BRIGHTNESS_KOVS	0x14
#define MICROP_COLOR_LED_STATE_KOVS		0x20
#define MICROP_LSENSOR_KOVS				0x30
#define MICROP_PATTERN_BUFFER_KOVS		0x41
#define MICROP_HEADSET_AMP_KOVS			0x80
#define	MICROP_OJ_RESET_KOVS			0xBA
#define	MICROP_OJ_REQUEST_KOVS			0xF0
#define	MICROP_OJ_ID_KOVS				0xF1
#define	MICROP_OJ_DATA_KOVS				0xF5
#define MICROP_LSENSOR_ENA_KOVS			0xF7

#define MICROP_KPD_LED_ENABLE_KOVS		0x30
#define MICROP_KPD_LED_BRIGHTNESS_KOVS	0x32

#endif
