#ifndef _MICROP_HTCKOVSKY_H
#define _MICROP_HTCKOVSKY_H

#define	MICROP_OJ_POWER_KOVS			0x03
#define MICROP_VERSION_REG_KOVS			0x07
#define MICROP_PATTERN_COMMAND_KOVS		0x11
#define MICROP_LCD_BRIGHTNESS_KOVS		0x12
#define MICROP_LCD_BRIGHTNESS_KOVS_13	0x13
#define MICROP_KEYPAD_BRIGHTNESS_KOVS	0x14
#define MICROP_COLOR_LED_STATE_KOVS		0x20
#define MICROP_LSENSOR_KOVS				0x30
#define MICROP_PATTERN_BUFFER_KOVS		0x41
#define MICROP_HEADSET_AMP_KOVS			0x80
#define	MICROP_OJ_RESET_KOVS			0xBA
#define	MICROP_OJ_REQUEST_KOVS			0xF0
#define	MICROP_OJ_ID_KOVS				0xF1
#define	MICROP_OJ_DATA_KOVS				0xF5
#define MICROP_LSENSOR_ENA_KOVS			0xF7

#define MICROP_KPD_LED_ENABLE_KOVS		0x30
#define MICROP_KPD_LED_BRIGHTNESS_KOVS	0x32

#endif
