#ifndef _MICROP_HTCKOVSKY_H
#define _MICROP_HTCKOVSKY_H

#define MICROP_VERSION_REG_KOVS		0x07
#define MICROP_LED_STATE_KOVS		0x20
#define MICROP_LCD_BRIGHTNESS_KOVS	0x12
#define MICROP_KEYPAD_BRIGHTNESS_KOVS	0x14

#endif
